sudo: required
dist: precise
language: node_js
node_js:
    - "7"
    - "8"
script: npm test
notifications:
    email:
        recipients:
            - zlatkofedor@cherrysro.com
        on_success: change
        on_failure: always
services:
  - mongodb
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS rbac;'
